blank_issues_enabled: false
contact_links:
  - name: ‚ùì Questions / Support
    url: https://github.com/pennowtech/finflow/discussions
    about: Please use GitHub Discussions for general questions.
